import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getAllCategories } from "./lib/actions";

import Navbar from "./UI/navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getAllCategories();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen flex flex-col`}
        suppressHydrationWarning
      >
        <Navbar categories={categories} />
        {children}
      </body>
    </html>
  );
}
